type Curriculum = {
  canBeConfirmed: boolean;
  id: number;
  teacherName: string;
  lessonName: string;
  teacherId: number;
  lessonId: number;
  lessonCourse: string;
  classRoom: string;
  remark: string;
  dayOfWeek: number;
  dateTimeStamp: number;
  startTimeStamp: number;
  endTimeStamp: number;
  year: number;
  month: number;
  day: number;
  hasConfirmed: boolean;
  status: string;
};
