/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  parent_calendar: () => import("@/views/_builtin/parent/calendar/index.vue"),
  "parent_confirm-student": () => import("@/views/_builtin/parent/confirm-student/index.vue"),
  parent_home: () => import("@/views/_builtin/parent/home/index.vue"),
  parent_lesson: () => import("@/views/_builtin/parent/lesson/index.vue"),
  parent_me: () => import("@/views/_builtin/parent/me/index.vue"),
  about: () => import("@/views/about/index.vue"),
  curriculum_calendar: () => import("@/views/curriculum/calendar/index.vue"),
  curriculum_curriculum: () => import("@/views/curriculum/curriculum/index.vue"),
  curriculum_detail: () => import("@/views/curriculum/detail/index.vue"),
  curriculum_manage: () => import("@/views/curriculum/manage/index.vue"),
  curriculum_teacher: () => import("@/views/curriculum/teacher/index.vue"),
  enrollment_manage: () => import("@/views/enrollment/manage/index.vue"),
  "function_hide-child_one": () => import("@/views/function/hide-child/one/index.vue"),
  "function_hide-child_three": () => import("@/views/function/hide-child/three/index.vue"),
  "function_hide-child_two": () => import("@/views/function/hide-child/two/index.vue"),
  "function_multi-tab": () => import("@/views/function/multi-tab/index.vue"),
  "function_online-user": () => import("@/views/function/online-user/index.vue"),
  function_oplog: () => import("@/views/function/oplog/index.vue"),
  function_request: () => import("@/views/function/request/index.vue"),
  "function_super-page": () => import("@/views/function/super-page/index.vue"),
  function_system: () => import("@/views/function/system/index.vue"),
  function_tab: () => import("@/views/function/tab/index.vue"),
  "function_toggle-auth": () => import("@/views/function/toggle-auth/index.vue"),
  home: () => import("@/views/home/index.vue"),
  lesson_manage: () => import("@/views/lesson/manage/index.vue"),
  manage_menu: () => import("@/views/manage/menu/index.vue"),
  manage_role: () => import("@/views/manage/role/index.vue"),
  "manage_user-detail": () => import("@/views/manage/user-detail/[id].vue"),
  manage_user: () => import("@/views/manage/user/index.vue"),
  message_log: () => import("@/views/message/log/index.vue"),
  "multi-menu_first_child": () => import("@/views/multi-menu/first_child/index.vue"),
  "multi-menu_second_child_home": () => import("@/views/multi-menu/second_child_home/index.vue"),
  plugin_barcode: () => import("@/views/plugin/barcode/index.vue"),
  plugin_charts_echarts: () => import("@/views/plugin/charts/echarts/index.vue"),
  plugin_copy: () => import("@/views/plugin/copy/index.vue"),
  plugin_editor_markdown: () => import("@/views/plugin/editor/markdown/index.vue"),
  plugin_editor_quill: () => import("@/views/plugin/editor/quill/index.vue"),
  plugin_icon: () => import("@/views/plugin/icon/index.vue"),
  plugin_map: () => import("@/views/plugin/map/index.vue"),
  plugin_print: () => import("@/views/plugin/print/index.vue"),
  plugin_swiper: () => import("@/views/plugin/swiper/index.vue"),
  plugin_video: () => import("@/views/plugin/video/index.vue"),
  score_manage: () => import("@/views/score/manage/index.vue"),
  student_manage: () => import("@/views/student/manage/index.vue"),
  system: () => import("@/views/system/index.vue"),
  "user-center": () => import("@/views/user-center/index.vue"),
};
